-- local heistfix = LevelsTweakData.init

-- function LevelsTweakData:init()
-- 	heistfix(self)
	
-- 	self.run.env_params = {
-- 		environment = "environments/pd2_env_hox_02/pd2_env_hox_02"
-- 	}
-- 	self.fish.env_params = {
-- 		environment = "environments/pd2_env_hox_02/pd2_env_hox_02"
-- 	}
-- 	self.man.env_params = {
-- 		environment = "environments/pd2_env_hox_02/pd2_env_hox_02"
-- 	}
-- 	self.pal.env_params = {
-- 		environment = "environments/pd2_env_hox_02/pd2_env_hox_02"
-- 	}
-- 	self.peta2.env_params = {
-- 		environment = "environments/pd2_env_hox_02/pd2_env_hox_02"
-- 	}
-- 	self.mad.env_params = {
-- 		environment = "environments/pd2_env_hox_02/pd2_env_hox_02"
-- 	}
-- end

-- if not PackageManager:loaded("levels/instances/unique/hlm_random_right003/world") then
-- 	PackageManager:load("levels/instances/unique/hlm_random_right003/world")
-- end
-- if not PackageManager:loaded("levels/instances/unique/hox_fbi_armory/world") then
-- 	PackageManager:load("levels/instances/unique/hox_fbi_armory/world")
-- end
-- if not PackageManager:loaded("levels/instances/unique/hlm_vault/world") then
-- 	PackageManager:load("levels/instances/unique/hlm_vault/world")
-- end
-- if not PackageManager:loaded("levels/instances/unique/hlm_gate_base/world") then
-- 	PackageManager:load("levels/instances/unique/hlm_gate_base/world")
-- end
-- if not PackageManager:loaded("levels/instances/unique/hlm_reader/world") then
-- 	PackageManager:load("levels/instances/unique/hlm_reader/world")
-- end
-- if not PackageManager:loaded("levels/instances/unique/hlm_door_wooden_white_green/world") then
-- 	PackageManager:load("levels/instances/unique/hlm_door_wooden_white_green/world")
-- end
-- if not PackageManager:load( "levels/narratives/vlad/ukrainian_job/world_sounds" ) then
-- 	PackageManager:load( "levels/narratives/vlad/ukrainian_job/world_sounds" )
-- 	PackageManager:load( "levels/narratives/vlad/jewelry_store/world_sounds" )
-- end